[package]
name = "fbi"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
image = "0.24.5"
multicache = "0.6.1"
# pixels = "0.11.0"
softbuffer = "0.2.0"
thiserror = "1.0.38"
winit = "0.28.2"
fast_image_resize = "2.6.0"
walkdir = "2.3.3"

[dev-dependencies]
minifb = "0.24.0"
